[package]
name = "jawir"
version = "0.1.0"
edition = "2021"

[lib]
path = "lib/lib.rs"

[dependencies]
base64 = "0.22.1"
clap = { version = "4.5.32", features = ["derive"] }
jsonwebtoken = "9.3.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
